patch:
  schema_list:
    - schema: luna_pinyin_simp
  caption: "〔切换〕"
  switcher:
    hotkeys:
      - Control+grave
      - Shift+Control+grave
      - F4

  menu:
    page_size: 5

  ascii_composer/good_old_caps_lock: true
  ascii_composer/switch_key:
   Shift_L: inline_ascii



      
      